# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Colour
version:      1.03
version_from: lib/Acme/Colour.pm
installdirs:  site
requires:
    Error:                         0.15
    Graphics::ColorNames:          0
    List::Util:                    0
    Module::Build:                 0.20
    Test::Exception:               0.15
    Test::More:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
