--- #YAML:1.0
name:                Acme-Colour
version:             1.04
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Error:                         0.15
    Graphics::ColorNames:          0
    List::Util:                    0
    Module::Build:                 0.20
    Test::Exception:               0.15
    Test::More:                    0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
